# -*- coding: utf-8 -*-
"""Data cleaning in pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BU9hECAS9Ei-xdE35LT2wbycXg1H9JcA
"""

import pandas as pd
df = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv')
df

df.drop_duplicates()

df = df.drop(columns = 'deck')
df

df['class'] = df['class'].str.strip(...)
df

df['fare'].astype(str).str.replace('[^a-ZA-Z0-9]','')
df

df['class'] = df['class'].astype(str).str.replace('NaN','')
df['class'] = df['class'].astype(str).str.replace('nan','')
df

df

df['fare'] = df['fare'].replace('.','')
df

df['alone'].str.replace('y','yes').str.replace('n','no')

for x in df.index:
  if df.loc[x,'alone'] == 'y':
    df.drop(x,inplace=True)
df

df = df.reset_index(drop=True)
df